kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: comments
spec:
  path: /
  to:
    kind: Service
    name: comments
    weight: 100
  port:
    targetPort: 4001-tcp
  wildcardPolicy: None